set_property PACKAGE_PIN E3 [get_ports clk_sys]
set_property PACKAGE_PIN M17 [get_ports rst_sys]
set_property PACKAGE_PIN L16 [get_ports en_sys]
set_property PACKAGE_PIN J15 [get_ports dir_sys]
set_property PACKAGE_PIN P18 [get_ports down_sys]
set_property PACKAGE_PIN M18 [get_ports up_sys]
set_property PACKAGE_PIN M13 [get_ports mode_sys]
set_property PACKAGE_PIN H16 [get_ports out_sys[0]]
set_property PACKAGE_PIN G13 [get_ports out_sys[1]]
set_property PACKAGE_PIN F13 [get_ports out_sys[2]]
set_property PACKAGE_PIN E16 [get_ports out_sys[3]]


set_property IOSTANDARD LVCMOS33 [get_ports clk_sys]
set_property IOSTANDARD LVCMOS33 [get_ports rst_sys]
set_property IOSTANDARD LVCMOS33 [get_ports en_sys]
set_property IOSTANDARD LVCMOS33 [get_ports dir_sys]
set_property IOSTANDARD LVCMOS33 [get_ports down_sys]
set_property IOSTANDARD LVCMOS33 [get_ports up_sys]
set_property IOSTANDARD LVCMOS33 [get_ports mode_sys]
set_property IOSTANDARD LVCMOS33 [get_ports out_sys[0]]
set_property IOSTANDARD LVCMOS33 [get_ports out_sys[1]]
set_property IOSTANDARD LVCMOS33 [get_ports out_sys[2]]
set_property IOSTANDARD LVCMOS33 [get_ports out_sys[3]]
