set_property PACKAGE_PIN E3 [get_ports clk]
set_property PACKAGE_PIN M17 [get_ports rst]
set_property PACKAGE_PIN L16 [get_ports en]
set_property PACKAGE_PIN J15 [get_ports direct]
set_property PACKAGE_PIN P18 [get_ports vup]
set_property PACKAGE_PIN M18 [get_ports vdown]
set_property PACKAGE_PIN H16 [get_ports teeth[0]]
set_property PACKAGE_PIN G13 [get_ports teeth[1]]
set_property PACKAGE_PIN F13 [get_ports teeth[2]]
set_property PACKAGE_PIN E16 [get_ports teeth[3]]


set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports en]
set_property IOSTANDARD LVCMOS33 [get_ports direct]
set_property IOSTANDARD LVCMOS33 [get_ports vup]
set_property IOSTANDARD LVCMOS33 [get_ports vdown]
set_property IOSTANDARD LVCMOS33 [get_ports teeth[0]]
set_property IOSTANDARD LVCMOS33 [get_ports teeth[1]]
set_property IOSTANDARD LVCMOS33 [get_ports teeth[2]]
set_property IOSTANDARD LVCMOS33 [get_ports teeth[3]]