webtalk_init -webtalk_dir D:/Study in SUSTech/Second semester of junior year/Digital system design/lab/lab2/exercise4/three_digit decimal counter/three_digi decimal counter.sim/sim_1/impl/func/xsim/xsim.dir/tb_clk_demical_counter_func_impl/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Mar 28 17:53:12 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "d0527d0a-a9fc-4227-9958-62d49e485bec" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "4534b72c0ee54a36bdf91c08cc6cdd85" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "13" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 5 4600H with Radeon Graphics         " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2994 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "200 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "4" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.26_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "8332_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3702959978 -regid "" -xml D:/Study in SUSTech/Second semester of junior year/Digital system design/lab/lab2/exercise4/three_digit decimal counter/three_digi decimal counter.sim/sim_1/impl/func/xsim/xsim.dir/tb_clk_demical_counter_func_impl/webtalk/usage_statistics_ext_xsim.xml -html D:/Study in SUSTech/Second semester of junior year/Digital system design/lab/lab2/exercise4/three_digit decimal counter/three_digi decimal counter.sim/sim_1/impl/func/xsim/xsim.dir/tb_clk_demical_counter_func_impl/webtalk/usage_statistics_ext_xsim.html -wdm D:/Study in SUSTech/Second semester of junior year/Digital system design/lab/lab2/exercise4/three_digit decimal counter/three_digi decimal counter.sim/sim_1/impl/func/xsim/xsim.dir/tb_clk_demical_counter_func_impl/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
