@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.2 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Tue May 09 10:58:16 +0800 2023
REM SW Build 3064766 on Wed Nov 18 09:12:45 MST 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
REM elaborate design
echo "xelab -wto e84112d4aa224feb8aa43d29c71a3a01 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot test_repetitive_func_synth xil_defaultlib.test_repetitive -log elaborate.log"
call xelab  -wto e84112d4aa224feb8aa43d29c71a3a01 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot test_repetitive_func_synth xil_defaultlib.test_repetitive -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
