set_property PACKAGE_PIN E3 [get_ports clk]
set_property PACKAGE_PIN M17 [get_ports reset]
set_property PACKAGE_PIN M18 [get_ports start]

set_property PACKAGE_PIN J15 [get_ports n[0]]
set_property PACKAGE_PIN L16 [get_ports n[1]]
set_property PACKAGE_PIN M13 [get_ports n[2]]
set_property PACKAGE_PIN R15 [get_ports n[3]]
set_property PACKAGE_PIN R17 [get_ports n[4]]
set_property PACKAGE_PIN T18 [get_ports n[5]]

set_property PACKAGE_PIN v11 [get_ports ready]

set_property PACKAGE_PIN H17 [get_ports output_final[0]]
set_property PACKAGE_PIN K15 [get_ports output_final[1]]
set_property PACKAGE_PIN J13 [get_ports output_final[2]]
set_property PACKAGE_PIN N14 [get_ports output_final[3]]
set_property PACKAGE_PIN R18 [get_ports output_final[4]]
set_property PACKAGE_PIN V17 [get_ports output_final[5]]
set_property PACKAGE_PIN U17 [get_ports output_final[6]]
set_property PACKAGE_PIN U16 [get_ports output_final[7]]
set_property PACKAGE_PIN V16 [get_ports output_final[8]]
set_property PACKAGE_PIN T15 [get_ports output_final[9]]
set_property PACKAGE_PIN U14 [get_ports output_final[10]]
set_property PACKAGE_PIN T16 [get_ports output_final[11]]
set_property PACKAGE_PIN V15 [get_ports output_final[12]]
set_property PACKAGE_PIN V14 [get_ports output_final[13]]
set_property PACKAGE_PIN V12 [get_ports output_final[14]]


set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports start]

set_property IOSTANDARD LVCMOS33 [get_ports n[0]]
set_property IOSTANDARD LVCMOS33 [get_ports n[1]]
set_property IOSTANDARD LVCMOS33 [get_ports n[2]]
set_property IOSTANDARD LVCMOS33 [get_ports n[3]]
set_property IOSTANDARD LVCMOS33 [get_ports n[4]]
set_property IOSTANDARD LVCMOS33 [get_ports n[5]]

set_property IOSTANDARD LVCMOS33 [get_ports ready]

set_property IOSTANDARD LVCMOS33 [get_ports output_final[0]]
set_property IOSTANDARD LVCMOS33 [get_ports output_final[1]]
set_property IOSTANDARD LVCMOS33 [get_ports output_final[2]]
set_property IOSTANDARD LVCMOS33 [get_ports output_final[3]]
set_property IOSTANDARD LVCMOS33 [get_ports output_final[4]]
set_property IOSTANDARD LVCMOS33 [get_ports output_final[5]]
set_property IOSTANDARD LVCMOS33 [get_ports output_final[6]]
set_property IOSTANDARD LVCMOS33 [get_ports output_final[7]]
set_property IOSTANDARD LVCMOS33 [get_ports output_final[8]]
set_property IOSTANDARD LVCMOS33 [get_ports output_final[9]]
set_property IOSTANDARD LVCMOS33 [get_ports output_final[10]]
set_property IOSTANDARD LVCMOS33 [get_ports output_final[11]]
set_property IOSTANDARD LVCMOS33 [get_ports output_final[12]]
set_property IOSTANDARD LVCMOS33 [get_ports output_final[13]]
set_property IOSTANDARD LVCMOS33 [get_ports output_final[14]]


