@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.2 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Mon Apr 10 02:59:40 +0800 2023
REM SW Build 3064766 on Wed Nov 18 09:12:45 MST 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
REM elaborate design
echo "xelab -wto 99a9ca0583d5466ba8e6e101e8b5e2d4 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot frequency_divider_tb_2_behav xil_defaultlib.frequency_divider_tb_2 -log elaborate.log"
call xelab  -wto 99a9ca0583d5466ba8e6e101e8b5e2d4 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot frequency_divider_tb_2_behav xil_defaultlib.frequency_divider_tb_2 -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
